[package]
name = "calculator-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vercel_runtime = { version = "1.1.0" }

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json"]
